export * from "./OnBoardingComponent";
export * from "./OnBoardingMainPage";
export * from "./OnBoardingSidebar";
export *  from "./OnBoardingNav";
export *  from "./OnBoardingStudentSidebarNav.jsx";
export *  from "./OnBoardingStudentMainPage.jsx";
export * from "./OnBoardingStudentNav.jsx";
export * from "./OnBoardingStudentSidebar.jsx";
export * from "./OnboardingComponentVerify"
export * from "./OnboardingGoogleVerify"