export const dates = [
  {
    month: 'November 2022',
    schedules: [
      {
        id: 1,
        agency: 'MEA',
        meeting: 'G20 HOMs event ',
        dates: '25-27 Nov',
        city: 'Port Blair, A&N Islands',
      },
    ],
  },
  {
    month: 'December 2022',
    schedules: [
      {
        id: 1,
        agency: 'MEA',
        meeting: '1st Sherpa Meeting ',
        dates: '4-7 Dec',
        city: 'Udaipur, Rajasthan',
      },
      {
        id: 2,
        agency: 'MEA',
        meeting: '1st Development Working Group Meeting ',
        dates: '13-16 Dec',
        city: 'Mumbai, Maharashtra',
      },
      {
        id: 3,
        agency: 'MoF',
        meeting: '1st Finance & Central Bank Deputies Meeting',
        dates: '13-15 Dec',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 4,
        agency: 'MoF',
        meeting: '1st Framework Working Group Meeting ',
        dates: '16-17 Dec',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 5,
        agency: 'MoF',
        meeting: '1st Joint Finance and Health Task Force Meeting ',
        dates: '20 Dec',
        city: 'Coming Soon...',
      },
    ],
  },
  /* */
  {
    month: 'Jaunuary 2023',
    schedules: [
      {
        id: 1,
        agency: 'MoF',
        meeting: '1st Meeting for the Global Partnership for Financial Inclusion',
        dates: '9-11 Jan',
        city: 'Kolkata, Wb',
      },
      {
        id: 2,
        agency: 'CII',
        meeting: 'B20 Inception Meeting',
        dates: '23-24 Jan',
        city: 'Gandhinagar, Gujarat',
      },
      {
        id: 3,
        agency: 'MoF',
        meeting: '1st Infrastructure Working Group Meeting ',
        dates: '16-17 Jan',
        city: 'Pune, Maharashtra',
      },
      {
        id: 4,
        agency: 'MEITY',
        meeting: 'DEWG event : Introductory Digital Economy',
        dates: '17-18 Jan',
        city: 'Coming Soon...',
      },
      {
        id: 5,
        agency: 'MoHFW',
        meeting: '1st Health Working Group Meeting',
        dates: '18-20 Jan',
        city: 'Thiruvanantha puram, Kerala',
      },
      {
        id: 6,
        agency: 'MEA',
        meeting: 'Think 20 Inception Meeting',
        dates: '13-15 Jan',
        city: 'New Delhi',
      },
      {
        id: 7,
        agency: 'DPIIT',
        meeting: 'StartUp20 Inception Meeting',
        dates: '28 Jan',
        city: 'Hyderabad, Telangana',
      },
      {
        id: 8,
        agency: 'MoF',
        meeting: '1st International Financial Architecture Working Group Meeting',
        dates: '30-31 Jan',
        city: 'Chandigarh',
      },
      {
        id: 9,
        agency: 'DST',
        meeting: 'Science 20 Inception Meeting',
        dates: '30-31 Jan',
        city: 'Puducherry',
      },
      {
        id: 10,
        agency: 'Min of Edu',
        meeting: '1st Education Working Group Meeting',
        dates: '31 Jan-2 Feb',
        city: 'Chennai, TN',
      },
    ],
  },
  {
    month: 'February 2023',
    schedules: [
      {
        id: 1,
        agency: 'DST',
        meeting: 'RIIG Inception(SERB)',
        dates: '8-9 Feb',
        city: 'Kolkata, Wb',
      },
      {
        id: 2,
        agency: 'CII',
        meeting: 'B20 Event',
        dates: '17-18 Feb',
        city: 'Imphal, Manipur',
      },
      {
        id: 3,
        agency: 'MoF',
        meeting: '1st Sustainable Finance Working Group Meeting',
        dates: '2-3 Feb',
        city: 'Guwahati, Assam',
      },
      {
        id: 4,
        agency: 'MMin of Labour & Employment',
        meeting: '1st Employment Working Group Meeting',
        dates: '2-4 Feb',
        city: 'Jodhpur, Rajasthan',
      },
      {
        id: 5,
        agency: 'Min of Power',
        meeting: '1st Energy Working Group Meeting',
        dates: '5-7 Feb ',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 6,
        agency: 'Min of Tourism',
        meeting: '1st Tourism Working Group Meeting',
        dates: '8-10 Feb',
        city: 'Rann Of Kutch, Gujarat',
      },
      {
        id: 7,
        agency: 'Min of Youth Affairs & Sports',
        meeting: 'Youth 20 Inception Meeting',
        dates: '6-8 Feb',
        city: 'Guwahati, Assam',
      },
      {
        id: 8,
        agency: 'MOEFCC',
        meeting: '1st Environment and Climate Working Group Meeting',
        dates: '9-11 Feb',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 9,
        agency: 'MWCD',
        meeting: 'G20 EMPOWER Inception',
        dates: '9-10 Feb',
        city: 'Agra, Uttar Pradesh',
      },
      {
        id: 10,
        agency: 'MoHUA',
        meeting: 'Urban 20 Inception Meeting',
        dates: '9-10 Feb',
        city: 'Ahmedabad, Gujarat,',
      },
      {
        id: 11,
        agency: 'Min of Agriculture',
        meeting: '1st Agriculture Working Group Meeting',
        dates: '13-15 Feb',
        city: 'Indore, MP',
      },
      {
        id: 12,
        agency: 'MWCD',
        meeting: 'Women 20 Inception Meeting',
        dates: '27-28 Feb',
        city: 'Aurangabad, Maharashtra',
      },
      {
        id: 13,
        agency: 'MEITY',
        meeting: '1st Digital Economy Working Group Meeting',
        dates: '13-15 Feb',
        city: 'Lucknow, UP',
      },
      {
        id: 14,
        agency: 'MoF',
        meeting: '2nd Finance & Central Bank Deputies Meeting',
        dates: '21-22 Feb',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 15,
        agency: 'MoF',
        meeting: '1st Finance Ministers and Central Bank Governors Meeting',
        dates: '23-25 Feb',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 16,
        agency: 'Min of Culture',
        meeting: '1st Culture Working Group Meeting',
        dates: '23-25 Feb',
        city: 'Khajuraho, MP',
      },
      {
        id: 17,
        agency: 'DST',
        meeting: 'Science 20 event;',
        dates: '27-28 Feb',
        city: 'Kavaratti, Lakshadweep',
      },
    ],
  },
  {
    month: 'March 2023',
    schedules: [
      {
        id: 1,
        agency: 'MEA',
        meeting: 'G20 Foreign Minister Meeting',
        dates: '1-2 Mar',
        city: 'Delhi',
      },
      {
        id: 2,
        agency: 'DPOT',
        meeting: '1st Anti-Corruption Working Group Meeting',
        dates: '1-3 Mar',
        city: 'Gurugram, Haryana',
      },
      {
        id: 3,
        agency: 'CII',
        meeting: 'B20 Event',
        dates: '1 Mar',
        city: 'Surat, Gujarat',
      },
      {
        id: 4,
        agency: 'CII',
        meeting: 'B20 Event',
        dates: '2 Mar',
        city: 'Aizawl, Mizoram',
      },
      {
        id: 5,
        agency: 'DST',
        meeting: 'RIIG event (CSIR)',
        dates: '2-3 Mar ',
        city: 'Ranchi, Jharkhand',
      },
      {
        id: 6,
        agency: 'MoF',
        meeting: '2nd Meeting for the Global Partnership for Financial Inclusion',
        dates: '6-7 Mar',
        city: 'Hyderabad, Telangana',
      },
      {
        id: 7,
        agency: 'MoLE',
        meeting: 'Labour 20 Inception Meeting',
        dates: '6-7 Mar',
        city: 'Patna, Bihar',
      },
      {
        id: 8,
        agency: 'MoF',
        meeting: '2nd Joint Finance and Health Task Force Meeting',
        dates: '10 Mar',
        city: 'Coming Soon...',
      },
      {
        id: 9,
        agency: 'CAG',
        meeting: 'SAI 20 Inception Meeting',
        dates: '13-15 Mar',
        city: 'Guwahati, Assam',
      },
      {
        id: 10,
        agency: 'MoF',
        meeting: '2nd Framework Working Group Meeting',
        dates: '14-16 Mar',
        city: 'Mahabalipuram, Tamil Nadu',
      },
      {
        id: 11,
        agency: 'MoE',
        meeting: '2nd Education Working Group Meeting',
        dates: '15-17 Mar',
        city: 'Amritsar, Punjab',
      },
      {
        id: 12,
        agency: 'CII',
        meeting: 'B20 Event',
        dates: '16 Mar',
        city: 'Gangtok, Sikkim',
      },
      {
        id: 13,
        agency: 'MEA',
        meeting: 'Civil20 Inception Meeting',
        dates: '20-21 Mar',
        city: 'Nagpur, Maharashtra',
      },
      {
        id: 14,
        agency: 'MoF',
        meeting: '2nd Sustainable Finance Working Group Meeting',
        dates: '21-23 Mar',
        city: 'Udaipur, Rajasthan',
      },
      {
        id: 15,
        agency: 'MEA',
        meeting: '2nd Sherpa Meeting',
        dates: '21-24 Mar',
        city: 'Kumarakom, Kerala',
      },
      {
        id: 16,
        agency: 'DST',
        meeting: 'RIIG event (DBT)',
        dates: '24-25 Mar',
        city: 'Dibrugarh/Itanagar, Arunachal Pradesh',
      },
      {
        id: 17,
        agency: 'MOEFCC',
        meeting: '2nd Environment and Climate Working Group Meeting',
        dates: '27-29 Mar',
        city: 'Gandhinagar, Gujarat',
      },
      {
        id: 18,
        agency: 'MEA',
        meeting: '2nd Development Working Group Meeting',
        dates: '28-31 Mar',
        city: 'Kumarakom, Kerala',
      },
      {
        id: 19,
        agency: 'DoC',
        meeting: '1st Trade & Investment Working Group Meeting',
        dates: '28-30 Mar',
        city: 'Mumbai, Maharashtra',
      },
      {
        id: 20,
        agency: 'MoF',
        meeting: '2nd Infrastructure Working Group Meeting',
        dates: '28-29 Mar',
        city: 'Visakhapatnam, Andhra Pradesh',
      },
      {
        id: 21,
        agency: 'Min of Agriculture',
        meeting: '2nd Agriculture Working Group Meeting',
        dates: '29-31 Mar',
        city: 'Chandigarh, Chandigarh',
      },
      {
        id: 22,
        agency: 'NDMA',
        meeting: '1st Disaster Management Working Group Meeting',
        dates: '30 Mar-01 Apr',
        city: 'Gandhinagar, Gujarat',
      },
    ],
  },
  {
    month: 'April 2023',
    schedules: [
      {
        id: 1,
        agency: 'CII',
        meeting: 'B20 Event',
        dates: '5 Apr',
        city: 'Dimapur, Nagaland',
      },
      {
        id: 2,
        agency: 'MoF',
        meeting: '2nd International Financial Architecture Working Group Meeting',
        dates: '',
        city: '',
      },
      {
        id: 3,
        agency: 'Min of Power',
        meeting: '2nd Energy Working Group Meeting',
        dates: '2-4 Apr',
        city: 'Gandhinagar, Gujarat',
      },
      {
        id: 4,
        agency: 'MoLE',
        meeting: '2nd Employment Working Group Meeting',
        dates: '3-5 Apr',
        city: 'Guwahati, Assam',
      },
      {
        id: 5,
        agency: 'DST',
        meeting: 'Science 20 event;',
        dates: '3-4 Apr',
        city: 'Agartala, Tripura',
      },
      {
        id: 6,
        agency: 'Min of Tourism',
        meeting: '2nd Tourism Working Group Meeting',
        dates: '3-5 Apr',
        city: 'Siliguri/Darjeeling, West Bengal',
      },
      {
        id: 7,
        agency: 'MWCD',
        meeting: 'G20 EMPOWER Meeting',
        dates: '5-6 Apr',
        city: 'PThiruvananthapuram, Kerala',
      },
      {
        id: 8,
        agency: 'MWCD',
        meeting: 'Women 20 Meeting',
        dates: '13-14 Apr',
        city: 'Jaipur, Rajasthan',
      },
      {
        id: 9,
        agency: 'MoHFW',
        meeting: '2nd Health Working Group Meeting',
        dates: '17-19 Apr',
        city: 'Goa, Goa',
      },
      {
        id: 10,
        agency: 'Min of Agriculture',
        meeting: 'Agri event - MACS',
        dates: '17-19 Apr',
        city: 'Varanasi, Uttar Pradesh',
      },
      {
        id: 11,
        agency: 'DoS',
        meeting: 'Space 20',
        dates: '17-18 Apr',
        city: 'Shillong, Meghalaya',
      },
      {
        id: 12,
        agency: 'DST',
        meeting: 'RIIG event (SERB)',
        dates: '19-20 Apr',
        city: 'Shimla, Himachal Pradesh',
      },
      {
        id: 13,
        agency: 'MoF',
        meeting: '2nd Finance Ministers and Central Bank Governors Meeting',
        dates: '',
        city: 'Washington Dc, Na',
      },
      {
        id: 14,
        agency: 'MoE',
        meeting: '3rd Education Working Group Meeting',
        dates: '24-27 Apr',
        city: 'Bhubaneswar, Odisha',
      },
      {
        id: 15,
        agency: 'MEITY',
        meeting: '2nd Digital Economy Working Group Meeting',
        dates: '26-28 Apr',
        city: 'Hyderabad, Telangana',
      },
      {
        id: 16,
        agency: 'MoYA&S',
        meeting: 'Youth 20 event',
        dates: '26-28 Apr',
        city: 'Leh, Ladakh',
      },
    ],
  },
  {
    month: 'May 2023',
    schedules: [
      {
        id: 1,
        agency: 'CII',
        meeting: 'B20 Event',
        dates: '10 May',
        city: 'Shimla, Himachal Pradesh',
      },
      {
        id: 2,
        agency: 'Min of Culture',
        meeting: '2nd Culture Working Group Meeting',
        dates: '15-17 May',
        city: 'Bhubaneswar, Odisha',
      },
      {
        id: 3,
        agency: 'Min of Power',
        meeting: '3rd Energy Working Group Meeting',
        dates: '15-17 May',
        city: 'Mumbai, Maharashtra',
      },
      {
        id: 4,
        agency: 'DST',
        meeting: 'RIIG event (MoES)',
        dates: '18-19 May',
        city: 'Diu, Dadra And Nagar Haveli Daman And Diu',
      },
      {
        id: 5,
        agency: 'NDMA',
        meeting: 'DRR Consultative Meeting',
        dates: '18-20 May',
        city: 'Mumbai, Maharashtra',
      },
      {
        id: 6,
        agency: 'MOEFCC',
        meeting: '3rd Environment and Climate Working Group Meeting',
        dates: '21-23 May',
        city: 'Mumbai, Maharashtra',
      },
      {
        id: 7,
        agency: 'Min of Tourism',
        meeting: '3rd Tourism Working Group Meeting',
        dates: '22-24 May',
        city: 'Srinagar, Jammu & Kashmir',
      },
      {
        id: 8,
        agency: 'DOPT',
        meeting: '2nd Anti-Corruption WG Meeting',
        dates: '25-27 May',
        city: 'Rishikesh, Uttarakhand',
      },
      {
        id: 9,
        agency: 'MoHUA',
        meeting: 'Urban 20 Summit',
        dates: '29-30 May',
        city: 'Ahmedabad, Gujarat',
      },
    ],
  },
  {
    month: 'June 2023',
    schedules: [
      {
        id: 1,
        agency: 'CAG',
        meeting: 'SAI 20 Summit',
        dates: '12-14 Jun',
        city: 'Goa, Goa',
      },
      {
        id: 2,
        agency: 'MoLE',
        meeting: '3rd Employment Working Group Meeting',
        dates: '1-2 Jun',
        city: 'Geneva (International)',
      },
      {
        id: 3,
        agency: 'MWCD',
        meeting: 'G20 EMPOWER Summit',
        dates: '1-2 Jun',
        city: 'Indore, MP',
      },
      {
        id: 4,
        agency: 'Parliament',
        meeting: 'Parliament 20 Summit',
        dates: '5-6 Jun',
        city: 'Delhi',
      },
      {
        id: 5,
        agency: 'MoF',
        meeting: '3rd International Financial Architecture Working Group Meeting',
        dates: '5-7 Jun',
        city: 'Goa',
      },
      {
        id: 6,
        agency: 'MoHFW',
        meeting: '3rd Health Working Group Meeting',
        dates: '7-9 Jun',
        city: 'Hyderabad, Telangana',
      },
      {
        id: 7,
        agency: 'MoYA&S',
        meeting: 'Youth 20 Summit',
        dates: '',
        city: 'Varanasi, UP',
      },
      {
        id: 8,
        agency: 'MEA',
        meeting: '3rd Development Working Group Meeting',
        dates: '',
        city: 'Goa',
      },
      {
        id: 9,
        agency: 'MoF',
        meeting: '3rd Framework Working Group Meeting',
        dates: '12-14 Jun',
        city: 'Kochi, Kerala',
      },
      {
        id: 10,
        agency: 'MEITY',
        meeting: '3rd Digital Economy Working Group Meeting',
        dates: '12-14 Jun',
        city: 'Pune, Maharashtra',
      },
      {
        id: 11,
        agency: 'MEA',
        meeting: 'Development Working Group MM',
        dates: '14 Jun',
        city: 'Varanasi, UP',
      },
      {
        id: 12,
        agency: 'Min of Agriculture',
        meeting: '3rd Agriculture Working Group Meeting',
        dates: '15-17 Jun',
        city: 'Hyderabad, Telangana',
      },
      {
        id: 13,
        agency: 'MEA',
        meeting: 'Joint Development and Foreign MM',
        dates: '15 Jun',
        city: 'Varanasi, Uttar Pradesh',
      },
      {
        id: 14,
        agency: 'DST',
        meeting: 'Science 20 event;',
        dates: '16-17 Jun',
        city: 'Bhopal, Madhya Pradesh',
      },
      {
        id: 15,
        agency: 'Min of Agriculture',
        meeting: 'Agriculture Working Group MM',
        dates: '17 Jun',
        city: 'Hyderabad, Telangana',
      },
      {
        id: 16,
        agency: 'Min of Tourism',
        meeting: '4th Tourism Working Group Meeting',
        dates: '19-20 Jun',
        city: 'Goa, Goa',
      },
      {
        id: 17,
        agency: 'DoC',
        meeting: '2nd Trade & Investment Working Group Meeting',
        dates: '19-21 Jun',
        city: 'Kevadia, Gujarat',
      },
      {
        id: 18,
        agency: 'MoF',
        meeting: '3rd Sustainable Finance Working Group Meeting',
        dates: '19-21 Jun',
        city: 'Mahabalipuram, Tamil Nadu',
      },
      {
        id: 19,
        agency: 'MWCD',
        meeting: 'Women 20 Summit',
        dates: '15-16 Jun',
        city: 'Mahabalipuram, Tamil Nadu',
      },
      {
        id: 20,
        agency: 'Min of Tourism',
        meeting: 'Tourism Working Group MM',
        dates: '21-22 Jun',
        city: 'Goa, Goa',
      },
      {
        id: 21,
        agency: 'MoLE',
        meeting: 'Labour 20 Summit',
        dates: '22-23 Jun',
        city: 'Amritsar, Punjab',
      },
      {
        id: 22,
        agency: 'MEA',
        meeting: '3Think 20 Summit',
        dates: '22-23 Jun',
        city: 'Mysuru, Karnataka',
      },
      {
        id: 23,
        agency: 'MoE',
        meeting: '4th Education Working Group Meeting ',
        dates: '25-27 Jun',
        city: 'Pune, Maharashtra',
      },
      {
        id: 24,
        agency: 'MoF',
        meeting: '3rd Infrastructure Working Group Meeting',
        dates: '26-28 Jun',
        city: 'Rishikesh, Uttarakhand',
      },
      {
        id: 25,
        agency: 'MoE',
        meeting: 'Education Working Group MM',
        dates: '28 Jun',
        city: 'Pune, Maharashtra',
      },
    ],
  },
  {
    month: 'July 2023',
    schedules: [
      {
        id: 1,
        agency: 'DST',
        meeting: 'Science 20 Summit',
        dates: '21-22 Jul',
        city: 'Coimbatore, Tamil Nadu',
      },
      {
        id: 2,
        agency: 'MEA',
        meeting: '4th Development Working Group Meeting',
        dates: '11-13 Jul',
        city: 'Varanasi, Uttar Pradesh',
      },
      {
        id: 3,
        agency: 'MoF',
        meeting: '3rd GPFI Meeting',
        dates: '3-5 Jul',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 4,
        agency: 'DPIIT',
        meeting: 'StartUp20 Summit Meeting',
        dates: '3 Jul',
        city: 'Gurugram, Haryana',
      },
      {
        id: 5,
        agency: 'DST',
        meeting: 'RIIG Summit',
        dates: '4-5 Jul',
        city: 'Mumbai, Maharashtra',
      },
      {
        id: 6,
        agency: 'DoS',
        meeting: 'Space 20 SELM',
        dates: '6-7 Jul',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 7,
        agency: 'DST',
        meeting: 'Research Ministers Meeting ',
        dates: '6 Jul',
        city: 'Mumbai, Maharashtra',
      },
      {
        id: 8,
        agency: 'MEA',
        meeting: '3rd Sherpa Meeting',
        dates: '10-12 Jul',
        city: 'Hampi, Karnataka',
      },
      {
        id: 9,
        agency: 'DoC',
        meeting: '3rd Trade & Investment Working Group',
        dates: '13-15 Jul',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 10,
        agency: 'Min of Culture',
        meeting: '3rd Culture Working Group Meeting',
        dates: '16-18 Jul',
        city: 'Hampi, Karnataka',
      },
      {
        id: 11,
        agency: 'MoF',
        meeting: '3rd Joint Finance and Health Task Force Meeting',
        dates: '18-Jul',
        city: 'To Be Indicated',
      },
      {
        id: 12,
        agency: 'Min of Power',
        meeting: '4th Energy Working Group Meeting',
        dates: '19-20 Jul',
        city: 'Goa',
      },
      {
        id: 13,
        agency: 'Min of Labour & Employment',
        meeting: '4th Employment Working Group Meeting',
        dates: '19-20 Jul',
        city: 'Indore, MP',
      },
      {
        id: 14,
        agency: 'MoF',
        meeting: '3rd Finance and Central Bank Deputies Meeting',
        dates: '21-23 Jul',
        city: 'Gandhinagar, Gujarat',
      },
      {
        id: 15,
        agency: 'Min of Labour & Employment',
        meeting: 'Labour and Employment Ministers’ Meeting',
        dates: '21 Jul',
        city: 'Indore, MP',
      },
      {
        id: 16,
        agency: 'Min of Power',
        meeting: 'Energy Working Group MM',
        dates: '22 Jul',
        city: 'Goa',
      },
      {
        id: 17,
        agency: 'NDMA',
        meeting: '2nd Disaster Management WG',
        dates: '24-26 Jul',
        city: 'Chennai, TN',
      },
      {
        id: 18,
        agency: 'MOEFCC',
        meeting: '4th Environment and Climate Working Group Meeting',
        dates: '26-27 Jul',
        city: 'Chennai, TN',
      },
      {
        id: 19,
        agency: 'MOEFCC',
        meeting: 'Environment and Climate Working Group MM',
        dates: '28 Jul',
        city: 'Chennai, TN',
      },
      {
        id: 20,
        agency: 'MEA',
        meeting: 'Civil 20 Summit',
        dates: '30-31 Jul',
        city: 'Jaipur, Rajasthan',
      },
    ],
  },
  {
    month: 'August 2023',
    schedules: [
      {
        id: 1,
        agency: 'MoF',
        meeting: 'Joint Meeting - Health & Finance Ministers',
        dates: '',
        city: 'Gandhinagar, Gujarat',
      },
      {
        id: 2,
        agency: 'MoHFW',
        meeting: '4th Health Working Group',
        dates: '2-3 Aug',
        city: 'Gandhinagar, Gujarat',
      },
      {
        id: 3,
        agency: 'MoHFW',
        meeting: 'Health Working Group MM',
        dates: '4 Aug',
        city: 'Gandhinagar, Gujarat',
      },
      {
        id: 4,
        agency: 'MWCD',
        meeting: 'Ministerial Meeting on Women Empowerment',
        dates: '9-11 Aug',
        city: 'Gandhinagar, Gujarat',
      },
      {
        id: 5,
        agency: 'MEITY',
        meeting: '4th Digital Economy Working Group Meeting',
        dates: '16-18 Aug',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 6,
        agency: 'CII',
        meeting: 'B20 Summit',
        dates: '18-19 Aug',
        city: 'Tbc, Na',
      },
      {
        id: 7,
        agency: 'MEITY',
        meeting: 'Digital Economy Working Group MM',
        dates: '19 Aug',
        city: 'Bengaluru, Karnataka',
      },
      {
        id: 8,
        agency: 'Min of Culture',
        meeting: '4th Culture Working Group meeting',
        dates: '21-22 Aug',
        city: 'Agra, UP',
      },
      {
        id: 9,
        agency: 'DoC',
        meeting: '34th Trade & Investment Working Group ',
        dates: '21-22 Aug',
        city: 'Jaipur, Rajasthan',
      },
      {
        id: 10,
        agency: 'Min of Culture',
        meeting: 'Culture Working Group MM ',
        dates: '23 Aug',
        city: 'Agra, UP',
      },
      {
        id: 11,
        agency: 'DoC',
        meeting: 'Trade & Investment Ministers’ Meeting',
        dates: '24-25 Aug',
        city: 'Jaipur, Rajasthan',
      },
      {
        id: 12,
        agency: 'DOPT',
        meeting: '3rd Anti-Corruption Working Group Meeting',
        dates: '28-30 Aug',
        city: 'Intl Venue, Na',
      },
      {
        id: 13,
        agency: 'MoF',
        meeting: '4th Sustainable Finance Working Group Meeting',
        dates: '28-29 Aug',
        city: 'Varanasi, UP',
      },
    ],
  },
  {
    month: 'September 2023',
    schedules: [
      {
        id: 1,
        agency: 'MEA',
        meeting: '4th Sherpa Meeting',
        dates: '3-6 September',
        city: 'Delhi',
      },
      {
        id: 2,
        agency: 'MoF',
        meeting: '4th Finance and Central Bank Deputies Meeting',
        dates: '5-6 September',
        city: 'Delhi',
      },
      {
        id: 3,
        agency: 'MoF',
        meeting: 'Joint Sherpas and Finance Deputies Meeting',
        dates: '06-Sep',
        city: 'Delhi',
      },
      {
        id: 4,
        agency: 'MoF',
        meeting: 'Joint Finance and Energy Deputies',
        dates: '07-Sep',
        city: 'Delhi',
      },
      {
        id: 5,
        agency: 'MoF',
        meeting: 'Joint Finance and Energy Ministers',
        dates: '08-Sep',
        city: 'Delhi',
      },
      {
        id: 6,
        agency: 'MEA',
        meeting: 'G20 Summit',
        dates: '9-10 Sep',
        city: 'Delhi',
      },
      {
        id: 7,
        agency: 'MoF',
        meeting: '4th Meeting for the Global Partnership for Financial Inclusion',
        dates: '15-16 September',
        city: 'Mumbai,Maharashtra',
      },
      {
        id: 8,
        agency: 'MoF',
        meeting: '4th Infrastructure Working Group Meeting',
        dates: '19-20 September',
        city: 'Khajuraho, MP',
      },
      {
        id: 9,
        agency: 'MoF',
        meeting: '4th Framework Working Group Meeting',
        dates: '22-23 September',
        city: 'Raipur, Chhattisgarh',
      },
      {
        id: 10,
        agency: 'MoF',
        meeting: '4th International Financial Architecture Working Group Meeting',
        dates: '29-30 September',
        city: 'Gandhinagar, Gujarat',
      },
    ],
  },
  {
    month: 'October 2023',
    schedules: [
      {
        id: 1,
        agency: 'MoF',
        meeting: '5th FCBD',
        dates: '10-Oct',
        city: 'Marrakesh, NA',
      },
      {
        id: 2,
        agency: 'MoF',
        meeting: '4th Finance Ministers and Central Bank Governors Meeting',
        dates: '11-12 Oct',
        city: 'Marrakesh, NA',
      },
    ],
  },
  {
    month: 'November 2023',
    schedules: [
      {
        id: 1,
        agency: 'MoF',
        meeting: 'Joint Finance and Enviro Ministers',
        dates: '6-17 Nov',
        city: 'COP 28 sidelines, NA',
      },
    ],
  },
];
